version: '3.8'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # Для S3 API
      - "9090:9090" # Для веб-интерфейса
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432" # Порт PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ctm
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
